name: Build

on:
  push:
    branches: [ main ]
    tags: [ "*" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/cmake-build-${{lowercase(env.BUILD_TYPE)}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/cmake-build-${{lowercase(env.BUILD_TYPE)}} --config ${{env.BUILD_TYPE}}

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/cmake-build-${{lowercase(env.BUILD_TYPE)}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/cmake-build-${{lowercase(env.BUILD_TYPE)}} --config ${{env.BUILD_TYPE}}
