name: Build

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Transform BUILD_TYPE string
        id: build_type_string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ env.BUILD_TYPE }}

      - name: Setup ENV
        run: |
          echo "BUILD_TYPE_LOWER=${{ steps.build_type_string.outputs.lowercase }}" >> ${GITHUB_ENV}
          echo "BUILD_DIR=${{ github.workspace }}/cmake-build-${{ env.BUILD_TYPE_LOWER }}" >> ${GITHUB_ENV}

      - name: Configure CMake
        run: cmake -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

      - name: Test
        timeout-minutes: 2
        run: |
          $BUILD_DIR/kmeans_seq 1 10 data/dataset-10000.txt data/dataset-10000.10.kmeans.txt
          $BUILD_DIR/kmeans_ver3 10 10 data/dataset-10000.txt data/dataset-10000.10.kmeans.txt
  

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Transform BUILD_TYPE string
        id: build_type_string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ env.BUILD_TYPE }}

      - name: Setup ENV
        run: |
          echo "BUILD_TYPE_LOWER=${{ steps.build_type_string.outputs.lowercase }}" >> $env:GITHUB_ENV
          echo "BUILD_DIR=${{ github.workspace }}/cmake-build-${{ env.BUILD_TYPE_LOWER }}" >> $env:GITHUB_ENV

      - name: Configure CMake
        run: cmake -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

      - name: Test
        timeout-minutes: 2
        run: |
          ${{ env.BUILD_DIR }}/${{ env.BUILD_TYPE }}/kmeans_seq.exe 1 10 data/dataset-10000.txt data/dataset-10000.10.kmeans.txt
          ${{ env.BUILD_DIR }}/${{ env.BUILD_TYPE }}/kmeans_ver3.exe 10 10 data/dataset-10000.txt data/dataset-10000.10.kmeans.txt