name: Build

on:
  push:
    branches: [ main ]
    tags: [ "*" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup ENV
        run: |
          echo "BUILD_TYPE_LOWER=${BUILD_TYPE,,}" >> ${GITHUB_ENV}
          echo "BUILD_DIR=${{ github.workspace }}/cmake-build-${{ env.BUILD_TYPE_LOWER }}" >> ${GITHUB_ENV}

      - name: Configure CMake
        run: cmake -B $BUILD_DIR -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

      - name: Build
        run: cmake --build $BUILD_DIR --config ${env.BUILD_TYPE}

      - name: Test
        run: |
          $BUILD_DIR/kmeans_seq 1 10 data/dataset-10000.txt

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup ENV
        run: |
          echo "BUILD_TYPE_LOWER=${BUILD_TYPE,,}" >> ${GITHUB_ENV}
          echo "BUILD_DIR=${{ github.workspace }}/cmake-build-${{ env.BUILD_TYPE_LOWER }}" >> ${GITHUB_ENV}

      - name: Configure CMake
        run: cmake -B $BUILD_DIR -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

      - name: Build
        run: cmake --build $BUILD_DIR --config ${env.BUILD_TYPE}

      - name: Test
        run: |
          $BUILD_DIR/kmeans_seq.exe 1 10 data/dataset-10000.txt