name: Build

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B cmake-build-release -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build cmake-build-release --config Release

      - name: Test
        timeout-minutes: 2
        run: |
          echo "Running kmeans_seq..."
          cmake-build-release/kmeans_seq 1 10 data/dataset-10000.txt data/dataset-10000.10.kmeans.txt
          echo "Running kmeans_ver3..."
          cmake-build-release/kmeans_ver3 10 10 data/dataset-10000.txt data/dataset-10000.10.kmeans.txt
          echo "Running kmeans_par1_1..."
          cmake-build-release/kmeans_par1_1 10 10 data/dataset-10000.txt data/dataset-10000.10.kmeans.txt
          echo "Running kmeans_par1_2..."
          cmake-build-release/kmeans_par1_2 10 10 data/dataset-10000.txt data/dataset-10000.10.kmeans.txt
          echo "Running kmeans_parakmeans..."
          cmake-build-release/kmeans_parakmeans 10 10 data/dataset-10000.txt data/dataset-10000.10.kmeans.txt
  

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B cmake-build-release -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build cmake-build-release --config Release

      - name: Test
        timeout-minutes: 2
        run: |
          echo "Running kmeans_seq..."
          cmake-build-release/Release/kmeans_seq.exe 1 10 data/dataset-10000.txt data/dataset-10000.10.kmeans.txt
          echo "Running kmeans_ver3..."
          cmake-build-release/Release/kmeans_ver3.exe 10 10 data/dataset-10000.txt data/dataset-10000.10.kmeans.txt
          echo "Running kmeans_par1_1..."
          cmake-build-release/Release/kmeans_par1_1.exe 10 10 data/dataset-10000.txt data/dataset-10000.10.kmeans.txt
          echo "Running kmeans_par1_2..."
          cmake-build-release/Release/kmeans_par1_2.exe 10 10 data/dataset-10000.txt data/dataset-10000.10.kmeans.txt
          echo "Running kmeans_parakmeans..."
          cmake-build-release/Release/kmeans_parakmeans.exe 10 10 data/dataset-10000.txt data/dataset-10000.10.kmeans.txt
  
